#spring.datasource.url=jdbc:h2:file:/data/demo

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    dll-auto: update
  h2:
    console:
      enable: true